### ISSUE TITLE
au-2 logging requirements

### ISSUE THREAD

**Issue by hollyallen** [18F/before-you-ship#296] opened 2017-04-05 23:06 UTC
Add in this list of things that must be logged.

Audit Events (AU-2) : Determines that the information system is capable of auditing the following events: [Assignment: organization-defined auditable events];

AU-2a Parameter Requirement: Successful and unsuccessful account logon events, account management events, object access, policy change, privilege functions, process tracking, and system events.  For Web applications: all administrator activity, authentication checks, authorization checks, data deletions, data access, data changes, and permission changes.

**Comment by afeld** [comment] 2017-04-12 15:22
Duplicate of #284.

**Closed by afeld** 2017-04-12 15:22 UTC

**Comment by hollyallen** [comment] 2017-04-12 15:31
Thanks! Amazing.
